### ISSUE TITLE
bug: Incorrect information on loading contracts from `sol` file

### ISSUE THREAD

**Issue by Aviksaikat** [alloy-rs/book#56]
[Here](https://github.com/alloy-rs/book/blob/3bdd820d0f183d5aed095371184e6fb033ff10f3/src/highlights/the-sol!-procedural-macro.md?plain=1#L58) the method mentioned below is incorrect.

```rs
sol!(
    Counter,
    "artifacts/Counter.sol"
);
```

**Comment by zerosnacks** [comment]
Thanks for the report + fix, marking as closed by https://github.com/alloy-rs/book/pull/57
